apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app
  description: Demo application for RHDH integration testing
  annotations:
    argocd/app-name: demo-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=demo-app'
    backstage.io/kubernetes-id: demo-app
spec:
  type: service
  lifecycle: experimental
  owner: user:default/bugbiteme