apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: rhdh-gitops
type: Opaque
stringData:
  accounts.developer-hub.password: "$2y$10$KnsgxceFRwN15iVJ3BxskuIJ2/qUqzaLs8.Oea1WzyvBraZxdG.eu"